contentColumnType: string
fieldGroup: bc97ed14-3643-4b76-bea5-9e7c4c684bcd
handle: footerInfo
instructions: ''
name: 'Footer Info'
searchable: false
settings:
  contentTable: '{{%stc_footerinfo}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
