enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  2727cef7-b711-4772-9f76-de4d80c07905:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
