enableVersioning: true
handle: pages
name: Pages
propagationMethod: all
siteSettings:
  2727cef7-b711-4772-9f76-de4d80c07905:
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry
    uriFormat: '{slug}'
structure:
  maxLevels: 1
  uid: d6755c79-c76b-4e12-bb97-7f3eed7ee4ae
type: structure
